version: '3.8'

services:
  app:
    build: .
    container_name: devops-agent-backend
    restart: unless-stopped
    environment:
      - ENVIRONMENT=${ENVIRONMENT:-development}
      - PORT=8000
    ports:
      - "${APP_PORT:-8000}:8000"
    volumes:
      - .:/app
    networks:
      - app_network
    depends_on:
      - redis

  redis:
    image: redis:7-alpine
    container_name: devops-agent-redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - app_network

volumes:
  redis_data:
    driver: local

networks:
  app_network:
    driver: bridge