version: '3.8'

services:
  app:
    build:
      context: .
      target: development
    container_name: nest-devops-agent
    restart: unless-stopped
    environment:
      - NODE_ENV=${NODE_ENV:-development}
      - PORT=8000
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - MODEL_API_KEY=${MODEL_API_KEY}
      - MODEL=${MODEL:-openai/gpt-4o-mini}
      - MODEL_BASE_URL=${MODEL_BASE_URL:-https://openrouter.ai/api/v1}
    ports:
      - "${PORT:-8000}:8000"
    volumes:
      - .:/app
      - /app/node_modules
    networks:
      - app_network
    depends_on:
      - redis

  redis:
    image: redis:7-alpine
    container_name: nest-devops-redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - app_network

volumes:
  redis_data:
    driver: local

networks:
  app_network:
    driver: bridge

